# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Generated by Django 2.0 on 2018-05-13 23:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('paid', models.BooleanField()),
                ('exemption', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DebtInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(choices=[('1', 'IPC'), ('2', 'Café'), ('3', 'Outro')], max_length=1)),
                ('value', models.IntegerField()),
                ('penalty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('value', models.FloatField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('drink_coffee', models.BooleanField()),
                ('get_in', models.DateTimeField()),
                ('get_out', models.DateTimeField()),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='debt_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.DebtInfo'),
        ),
        migrations.AddField(
            model_name='debt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Student'),
        ),
        migrations.AddField(
            model_name='credit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Student'),
        ),
    ]
