# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='value',
        ),
        migrations.AddField(
            model_name='debt',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='exemption',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
