# Generated by Django 2.1 on 2018-08-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20180715_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'Débito individual', 'verbose_name_plural': 'Débitos Individuais'},
        ),
        migrations.AlterModelOptions(
            name='debtinfo',
            options={'verbose_name': 'Débito Geral', 'verbose_name_plural': 'Débitos Gerais'},
        ),
        migrations.AlterModelOptions(
            name='entrance',
            options={'verbose_name': 'Fluxo de Entrada e Saída', 'verbose_name_plural': 'Fluxo de Entrada e Saída'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('name',), 'verbose_name': 'PETiano', 'verbose_name_plural': 'PETianos'},
        ),
        migrations.AlterField(
            model_name='student',
            name='get_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
